apply plugin: 'com.android.library'

android {
    compileSdk 33

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 33
    }

    buildTypes {
        release {
            minifyEnabled false
            consumerProguardFiles 'consumer-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        abortOnError false
    }

    namespace 'com.stackof.flipclockv2.weather'
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
}
